apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment  
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx-pod
      env: dev
  template:
    metadata:
      labels:
        run: nginx-pod
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx:latest