apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    app: busybox
spec:
  containers:
  - name: busybox-container
    image: busybox
    env:
    - name: FIRSTNAME
      value: "John"
    - name: LASTNAME
      value: "Doe"
    command: ["sleep", "3600"]  # Keeps container running for 1 hour
  restartPolicy: Never
