apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-cm
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: config-volume
      mountPath: /tmp/
  volumes:
  - name: config-volume
    configMap:
      name: file-config