apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-init
  labels: 
    name: nginx-with-init
spec:
  # Init container that runs before main containers
  initContainers:
  - name: init-cont
    image: busybox
    command: ['sh', '-c', 'echo "Init container running..."; sleep 5; until nslookup myservice.default.svc.cluster.local; do echo "waiting for the svc to be up"; sleep 2; done']
  
  # Main containers
  containers:
  - name: main-container
    image: busybox
    command: ['sh','-c','echo the app is running && sleep 30']
    env:
      - name: FirstName   
        value: "ak"
        
  - name: sidecar
    image: busybox
    command: ['sh', '-c', 'while true; do echo Sidecar running...; sleep 10; done']


